spring:
  data:
    cassandra:
      keyspace-name: sales
      contact-points: ${CASSANDRA_HOST}
      port: ${CASSANDRA_PORT}

product:
  url: http://localhost:8080
  endpoints:
    by_id: /api/product/

server:
  port: 8081

